// <auto-generated />
namespace VOOQQ_APP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class kjkkjkjkj : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kjkkjkjkj));
        
        string IMigrationMetadata.Id
        {
            get { return "202007101240196_kjkkjkjkj"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
