// <auto-generated />
namespace VOOQQ_APP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddEDU : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEDU));
        
        string IMigrationMetadata.Id
        {
            get { return "202008300600135_AddEDU"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
