// <auto-generated />
namespace VOOQQ_APP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Availability : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Availability));
        
        string IMigrationMetadata.Id
        {
            get { return "202008300750179_Availability"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
