// <auto-generated />
namespace VOOQQ_APP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class pppp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pppp));
        
        string IMigrationMetadata.Id
        {
            get { return "202002021525470_[p[p[p[p"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
